# -*- coding: utf-8 -*-
"""viswanath_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rUI0pWl-T180HK2ogDSyTD6Dvipwouzq

# Basic Python

## 1. Split this string
"""

s = "Hi there Sam!"

x = s.split( )

"""*`italicized text`*## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.
"""

planet = "Earth"
diameter = 12742

print("{} earth is ",format("The diameter of")+("{}.kilometer".format("12742")))

"""## 3. In this nest dictionary grab the word "hello"
"""

d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

d['k1'][3]['tricky'][3]['target'][3]

"""# Numpy"""

import numpy as np

"""## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?
"""

array = np.zeros(10)

print(array)

"""## 5. Create an array of all the even integers from 20 to 35"""

array = np.arange(20,36,2)
print (array)

"""## 6. Create a 3x3 matrix with values ranging from 0 to 8"""

import numpy as np
x =  np.arange(0, 9).reshape(3,3)

"""## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])
"""

a = np.array([1,2,3])
b = np.array([4,5,6])
c = a,b
print(c)

"""# Pandas

## 8. Create a dataframe with 3 rows and 2 columns
"""

import pandas as pd

data = [['Akash',6001],['Praveen Raj',6018],['Viswanath',6304],['Harish',6007]]
df=pd.DataFrame(data,coloumns = ['Name','Reg.no'])
print(df)

"""## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023"""

dates = pd.date_range(start = '1-1-2023',end = '2-10-2023')
print(dates)

"""## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]
"""

lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

df = pd.DataFrame.from_records(lists)
print(df)